version: "3.3"
services:
  mariadb:
    container_name: maria_db
    image: mariadb:10.7.1-focal
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MARIADB_PASSWORD: root
      MARIADB_ROOT_HOST: localhost
      MARIADB_USER: admin
      MARIADB_DATABASE: database
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
